# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d45af4c8b320f028b09ef266aa78775e"
name = "kkk"
handle = "kkk-12"
application_url = "https://norwegian-la\ck-drunk-irc.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://norwegian-la\ck-drunk-irc.trycloudflare.com/auth/callback", "https://norwegian-la\ck-drunk-irc.trycloudflare.com/auth/shopify/callback", "https://norwegian-la\ck-drunk-irc.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
